// <auto-generated />
using System;
using ConnectAssessment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConnectAssessment.Data.Migrations
{
    [DbContext(typeof(ConnectAssessmentDbContext))]
    [Migration("20250818130602_SeedCustomers")]
    partial class SeedCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConnectAssessment.Data.Models.Entities.tbCustomer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("tbCustomers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            AccountNumber = "100001",
                            Branch = "Durban",
                            Name = "Nolwazi",
                            SurName = "Mthethwa"
                        },
                        new
                        {
                            CustomerId = 2,
                            AccountNumber = "100002",
                            Branch = "Johannesburg",
                            Name = "Thabo",
                            SurName = "Nkosi"
                        },
                        new
                        {
                            CustomerId = 3,
                            AccountNumber = "100003",
                            Branch = "Cape Town",
                            Name = "Ayesha",
                            SurName = "Khan"
                        },
                        new
                        {
                            CustomerId = 4,
                            AccountNumber = "100004",
                            Branch = "Pretoria",
                            Name = "Sipho",
                            SurName = "Zulu"
                        });
                });

            modelBuilder.Entity("ConnectAssessment.Data.Models.Entities.tbSettlementTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<decimal>("TransactionFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("tbSettlementTransactions");
                });

            modelBuilder.Entity("ConnectAssessment.Data.Models.Entities.tbSettlementTransaction", b =>
                {
                    b.HasOne("ConnectAssessment.Data.Models.Entities.tbCustomer", "Customer")
                        .WithMany("SettlementTransactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ConnectAssessment.Data.Models.Entities.tbCustomer", b =>
                {
                    b.Navigation("SettlementTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
